### ISSUE TITLE
node app.js后，打不开后台主页，前台拿不到数据

### ISSUE THREAD

**Issue by pengrongjie** [HarryChen0506/vue_mall#1]

**Comment by HarryChen0506** [comment]
后台服务项目放在 vue_mall/my-mall/server 文件夹下，需要使用vscode等IDE开发工具开启node后端服务，另外数据存储在mongodb里面，需要自己去安装

**Comment by pengrongjie** [comment]
mall数据库下没有goods和user数据，是要自己加进去吗，我自已插入了一个user实例，就可以登录了，但是要怎么增加所有的goods和user数据呢，让项目一运行就能像你给的网址演示那样，另外文件夹mock /goods.json ，与项目有联系吗

**Comment by HarryChen0506** [comment]
嗯，需要自己先加到mongodb数据库里。mock /goods.json 里面就有商品的数据，与项目无关，是当时做假接口时调试用的，你可以参考使用。至于其他user的数据，你自己编吧

**Comment by pengrongjie** [comment]
@HarryChen0506 不太行，我插入的数据，图片显示不出来，并且价格筛选也没有反应，你是怎么把数据全都存储都mongodb里的，用户哪里的数据格式不知道怎么写，我用robomongo的可视化数据库,能复制粘贴发给我吗
